14 google oauth check
projekt-fitnessapp/backend pull request #24
Opened 2022-09-30 16:16 UTC by HaseFlrn

2022-10-01 14:43 UTC, STAT1C-Sy commented
@HaseFlrn sieht gut aus @lumaghg ich glaube da ist ne neue env varibale drin

2022-10-01 16:20 UTC, lumaghg commented
@

> @HaseFlrn sieht gut aus @lumaghg ich glaube da ist ne neue env varibale drin

@STAT1C-Sy hab gestern schon zwei neue geadded

2022-10-02 08:12 UTC, lumaghg reviewed
@HaseFlrn Was passiert wenn verify() fehlschlägt? Dann wird next() ja nicht aufgerufen und nur der error auf die Konsole geschrieben, aber es wird keine response gesendet, oder? Oder übersehe ich da was?

2022-10-02 08:16 UTC, lumaghg requested changes

2022-10-02 08:16 UTC, lumaghg commented on src/middleware/auth.ts
> +  verify().then(next).catch(console.error);
```suggestion
  verify().then(next).catch(err => {
      console.error(err);
      res.status(401).send();
  });
```

2022-10-03 09:17 UTC, HaseFlrn commented on src/middleware/auth.ts
> +  verify().then(next).catch(console.error);
Aktuell ja, würde ein redirect zu account für einen login reinsetzen, wenn das team dann soweit ist

2022-10-03 10:14 UTC, lumaghg commented on src/middleware/auth.ts
> +  verify().then(next).catch(console.error);
Ah ja okay geht auch

2022-10-03 10:15 UTC, lumaghg approved these changes

2022-10-03 10:15 UTC, lumaghg commented
@HaseFlrn dann kannst du mergen

2022-10-03 13:08 UTC, merged