19 body endpoint
projekt-fitnessapp/backend pull request #47
Opened 2022-10-15 08:39 UTC by Vollomat

2022-10-16 07:09 UTC, STAT1C-Sy requested changes
Bitte überarbeiten wie in den Kommentaren beschrieben

2022-10-16 07:09 UTC, STAT1C-Sy commented on src/routes/body/body.controller.ts
> +    const userId = savedBody._id;
denke userId ist hier nicht ganz der richtige Variablenname

2022-10-16 07:09 UTC, STAT1C-Sy commented on src/routes/body/body.controller.ts
> +    const docs =  await Body.findById(req.query.userId)
ist irgendwie sichergestellt, das ich nur eigene Bodys abrufen kann?

2022-10-16 07:09 UTC, STAT1C-Sy commented on src/routes/body/body.router.ts
> +import { saveBody } from './body.controller';
die import statements kann man zusammenfassen zu `import { getBody, saveBody } from './body.controller'`

2022-10-16 07:09 UTC, STAT1C-Sy commented on test/body/body.test.ts
> +        var mongoose = require('mongoose');
bitte keine imports mit require machen sondern import mongoose from 'mongoose'; an den Anfang zu den anderen imports hinzufügen hat den gleichen Effekt

2022-10-16 07:09 UTC, STAT1C-Sy commented on test/body/body.test.ts
> +        expect(res.body == null);
warum ist der result body hier == null sollte der nicht gleich dem erzeugten doc sein?

2022-10-16 07:09 UTC, STAT1C-Sy commented on test/body/body.test.ts
> +            _id: objectId,
ich glaube bei create kann man das _id Feld nicht explizit setzen

2022-10-16 16:33 UTC, Vollomat commented on test/body/body.test.ts
> +        expect(res.body == null);
Stimmt, das habe ich falsch kopiert :)

2022-10-16 16:36 UTC, Vollomat commented on test/body/body.test.ts
> +            _id: objectId,
Tatsächlich funktioniert das, zumindest bei dem Test.

2022-10-16 16:39 UTC, Vollomat commented on src/routes/body/body.controller.ts
> +    const docs =  await Body.findById(req.query.userId)
Nein, ich bekomme ja nur eine UserID (BodyID?) laut Doku. Ich wüsste jetzt nicht, wie ich das anhand der zur Verfügung stehenden Daten überprüfen kann :/

2022-10-16 18:25 UTC, Vollomat commented on src/routes/body/body.controller.ts
> +    const docs =  await Body.findById(req.query.userId)
Fehler gefunden, ich habe _id und UserID verwechselt.

2022-10-16 18:44 UTC, Vollomat commented
Ich habe nochmal zusätzlich die Überprüfung nach dem neusten Eintrag der Body-Data zu einer UserID hinzugefügt, da keine Put-Methode definiert war

2022-10-17 07:47 UTC, STAT1C-Sy commented
@Vollomat resolvest du noch den conflict?

2022-10-17 08:31 UTC, Vollomat commented
> @Vollomat resolvest du noch den conflict?

Erledigt

2022-10-17 13:51 UTC, STAT1C-Sy approved these changes

2022-10-17 14:20 UTC, merged