16 trainingsession endpoint
projekt-fitnessapp/backend pull request #48
Opened 2022-10-15 16:18 UTC by juengeja

2022-10-15 16:22 UTC, juengeja commented
fixed linting error

2022-10-15 16:49 UTC, lumaghg requested changes

2022-10-15 16:49 UTC, lumaghg commented on src/schemas/training.day.ts
> +        exerciseId: { type: String, required: true },
Soll das hier auf das Exercise Model referenzieren? Wenn ja dann fehlt da die Referenz
```suggestion
        exerciseId: { type: Schema.Types.ObjectId , ref: 'Exercise' },
```

2022-10-15 16:49 UTC, lumaghg commented on src/types/db/execution.types.ts
> +    _id: mongoose.Schema.Types.ObjectId,
Muss die ID hier explizit getyped werden? Es wird ja eigentlich nur ExecutionDocument verwendet und durch Document <TExecution> wird die _id da ergänzt oder? Kann auch sein dass ich mich irre, am besten einfach mal austesten

2022-10-15 16:49 UTC, lumaghg commented on src/types/db/exercise.types.ts
>      _id: ObjectId,
Wie in TExecution => muss das hier explizit getyped werden?

2022-10-15 16:49 UTC, lumaghg commented on src/types/db/training.day.types.ts
> +        exerciseId: string,
```suggestion
        exerciseId: Schema.Types.ObjectId,
```

Sieht für mich nach einer Referenz auf ein anderes Model aus. Außerdem klingt mir exercise**s** eher nach einem Array

2022-10-15 16:49 UTC, lumaghg commented on test/trainingSession/trainingSession.test.ts
> +        {_id:"5099803df3f4948bd2f98577"}
```suggestion
      "5099803df3f4948bd2f98577"
```

2022-10-15 16:49 UTC, lumaghg commented on src/routes/trainingSession/trainingSession.controller.ts
> +                })
```suggestion
                    const ids = id;
                    const singleSession = await TrainingSession.find({_id: {$in: ids})
                    .populate({
                        path: 'executions',
                        populate: {
                            path: 'exercise',
                            model: 'Exercise'
                        }
                    }) 
```

[https://kb.objectrocket.com/mongo-db/the-mongoose-in-operator-1015](https://kb.objectrocket.com/mongo-db/the-mongoose-in-operator-1015)

2022-10-15 16:49 UTC, lumaghg commented on src/routes/trainingSession/trainingSession.controller.ts
> +            }
Wenn das id Feld der Request ein Array ist, dann wird nach den korrespondierenden Trainingssessions gesucht. Wenn das id Feld der Request kein Array ist, dann wird nach allen Trainingssessions für eine userId gesucht. 

Falls du entweder mehrere bestimmte Trainingssessions oder alle für einen user bekommen willst wäre das verständlich, dann solltest du aber bei der oberen Query noch hinzufügen, dass ein User nur seine eigenen Trainingssessions querien kann.  (Habs jetzt hier geschrieben und markiert, weil ich nicht zwei Kommentare übereinander wollte :D)

Ich persönlich spalte sowas immer in zwei routes auf, eine getSingle und eine getAll (jeweils mit User Protection) und wenn das Frontend 3 bestimmte Trainingssessions braucht, dann schicken sie halt 3 Anfragen an die getSingle Route. Ist aber Geschmackssache denke ich

2022-10-16 10:42 UTC, juengeja commented
Bearbeitet. Soll noch etwas angepasst werden?

2022-10-16 14:44 UTC, HaseFlrn approved these changes

2022-10-16 15:02 UTC, lumaghg commented
@projekt-fitnessapp/backend irgendwer muss hier mal die Konflikte resolven

2022-10-17 13:09 UTC, HaseFlrn commented
@lumaghg resolved

2022-10-17 13:16 UTC, lumaghg approved these changes

2022-10-17 13:16 UTC, merged