40 exercise api
projekt-fitnessapp/backend pull request #49
Opened 2022-10-16 08:21 UTC by HaseFlrn

2022-10-16 08:49 UTC, STAT1C-Sy requested changes
sind nur kleinigkeiten wenn du da keinen Bock drauf hast kannst du die auch so mergen eigentlich nur kosmetische Sachen

2022-10-16 08:49 UTC, STAT1C-Sy commented on src/routes/exercise/exercise.controller.ts
> +const validMuscles = ["abs", "calves", 'quads', 'lats', 'pectorals', 'glutes', 'hamstrings', 'adductors',"abductors", 'triceps','cardiovascular system', 'spine', 'upper back', 'biceps', 'delts', 'for
die kannst du in ein enum packen

2022-10-16 08:49 UTC, STAT1C-Sy commented on src/routes/exercise/exercise.controller.ts
> +      validMuscles.forEach((muscle) => {
das kann man über ein Filter schöner lösen (optional)

2022-10-16 08:49 UTC, STAT1C-Sy commented on src/routes/exercise/exercise.controller.ts
> +      validEquipment.forEach((equipment) => {
same here (aber auch nur optional)

2022-10-16 08:49 UTC, STAT1C-Sy commented on src/routes/exercise/exercise.controller.ts
> +    res.status(200).json(resBody);
den status kannst du bei 200er weglassen 200 ist der default wenn du res.json aufrufst

2022-10-16 08:49 UTC, STAT1C-Sy commented on test/exercise/exercise.test.ts
> +chai.use(deepEqualInAnyOrder);
der ist gut den muss ich mit mal merken

2022-10-16 08:49 UTC, STAT1C-Sy commented on test/exercise/exercise.test.ts
> +describe("Exercise Endpoint Tests", () => {
Tests sind sehr clean props dafür

2022-10-16 08:50 UTC, STAT1C-Sy commented on test/exercise/exercise.test.ts
> +describe("Exercise Endpoint Tests", () => {
> sind nur kleinigkeiten wenn du da keinen Bock drauf hast kannst du die auch so mergen eigentlich nur kosmetische Sachen

@HaseFlrn wenn du nichts korrigieren willst sag einfach bescheid dann approve ich direkt

2022-10-16 10:11 UTC, HaseFlrn commented on src/routes/exercise/exercise.controller.ts
> +      validMuscles.forEach((muscle) => {
done

2022-10-16 10:12 UTC, HaseFlrn commented on src/routes/exercise/exercise.controller.ts
> +      validEquipment.forEach((equipment) => {
done

2022-10-16 10:12 UTC, HaseFlrn commented on src/routes/exercise/exercise.controller.ts
> +    res.status(200).json(resBody);
done

2022-10-16 10:12 UTC, HaseFlrn commented on src/routes/exercise/exercise.controller.ts
> +const validMuscles = ["abs", "calves", 'quads', 'lats', 'pectorals', 'glutes', 'hamstrings', 'adductors',"abductors", 'triceps','cardiovascular system', 'spine', 'upper back', 'biceps', 'delts', 'for
passt mir so besser :S

2022-10-16 10:13 UTC, HaseFlrn commented on test/exercise/exercise.test.ts
> +chai.use(deepEqualInAnyOrder);
^^

2022-10-16 10:13 UTC, HaseFlrn commented on test/exercise/exercise.test.ts
> +describe("Exercise Endpoint Tests", () => {
bin dann durch ^^

2022-10-16 10:14 UTC, HaseFlrn commented
@Reviewer: Wenn alles passt gerne direkt mergen :)

2022-10-17 07:46 UTC, STAT1C-Sy approved these changes

2022-10-17 07:46 UTC, merged