18 trainingplan endpoint
projekt-fitnessapp/backend pull request #50
Opened 2022-10-16 08:44 UTC by juengeja

2022-10-16 09:03 UTC, STAT1C-Sy requested changes
Nur kleinigkeiten man merkt fortschritt Tests sind clean man merkt dass du dich damit mittlerweile (wenn auch gezwungenermaßen) auseinandergesetzt hast

2022-10-16 09:03 UTC, STAT1C-Sy commented on test/trainingPlan/trainingPlan.test.ts
> +
für das Deepequal hatte flo ne richtig gute Idee kannst du auch verwenden wenn du magst löst denke ich ein paar der Probleme https://github.com/projekt-fitnessapp/backend/pull/49#discussion_r996411171

2022-10-16 10:29 UTC, juengeja commented on test/server.test.ts
> +  test("Sets DB_URL in process.env :", async () => {
Ja

2022-10-16 10:37 UTC, juengeja commented on test/trainingPlan/trainingPlan.test.ts
> +
Das Modul will er bei mir nicht akzeptieren o.O

2022-10-17 17:39 UTC, juengeja commented
fixed

2022-10-17 17:47 UTC, juengeja commented
@HaseFlrn Kannst du mergen? ich darf nicht...

2022-10-17 17:49 UTC, STAT1C-Sy approved these changes

2022-10-17 17:49 UTC, STAT1C-Sy commented
@juengeja geht jetzt?

2022-10-17 17:59 UTC, juengeja commented
@STAT1C-Sy codecov/project fehlt noch, wie kann ich das anstoßen?

2022-10-17 18:23 UTC, merged